package com.example.test;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.Fragment;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.media.MediaPlayer;
import android.os.Bundle;
import android.preference.PreferenceManager;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.Scanner;

public class MainActivity extends AppCompatActivity {
    private int timePassed = 0;
    private Date currentDate;
    private SharedPreferences timePassedsp;
    private SharedPreferences.Editor editor;
    private DateFormat timeFormat = new SimpleDateFormat("HH:mm:ss",Locale.getDefault());
    private String timeText;
    private MediaPlayer mediaPlayer;
    private View loadingView;
    private MediaPlayer MediaPlayerArray[] = new MediaPlayer[4];
    private Bitmap LoadingBitmapArray[] = new Bitmap[703];
    private int i = 0;
    private Context context;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        this.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);
        getSupportActionBar().hide();
        currentDate = new Date();
        timeText = timeFormat.format(currentDate);
        timePassed = ((timeText.indexOf(0)*10+timeText.indexOf(1))*3600)+((timeText.indexOf(3)*10+timeText.indexOf(4))*60)+((timeText.indexOf(6)*10+timeText.indexOf(7)));
        timePassedsp = getApplicationContext().getSharedPreferences("TIMEPASSED", MODE_PRIVATE);
        editor = timePassedsp.edit();
        mediaPlayer = MediaPlayer.create(this, R.raw.songfon);
        mediaPlayer.start();
        loadingView = getLayoutInflater().inflate(R.layout.activity_splash, null);
        context = this;
        new Thread(new Runnable() {
            @Override
            public void run() {
                loadGameResources();
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        setContentView(new MyDraw(context, timePassed - timePassedsp.getInt("TIMEPASSED",timePassed),LoadingBitmapArray));
                    }
                });
            }
        }).start();
    }
    private void loadGameResources() {
        Context context = this.context;
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.sovorakan1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.sovorakan2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_t_s_h_1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_t_s_h_2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_t_s_1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_t_s_2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_t_h_1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_t_h_2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_s_h_1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_s_h_2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.t_s_h_1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.t_s_h_2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_h_1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_h_2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_s_1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_s_2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_t_1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_t_2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.s_h_1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.s_h_2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.t_h_1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.t_h_2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.t_s_1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.t_s_2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.kextot1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.kextot2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.hognac1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.hognac2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.txur1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.txur2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.sovac1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.sovac2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.urax1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.urax2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.utox1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.utox2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.utox3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.utox4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.utox5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.utox6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.utox7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.utox8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.utox9);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.utox10);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.xaxacox1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.xaxacox2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.xaxacox3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.xaxacox4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.xaxacox5);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.xaxacox6);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.xaxacox7);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.xaxacox8);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.xaxacox9);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.xaxacox10);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.xaxacox11);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.xaxacox12);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.xaxacox13);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.xaxacox14);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.xaxacox15);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.xaxacox16);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.xaxacox17);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.xaxacox18);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.t_xaxacox19);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.t_xaxacox20);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_xaxacox1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_xaxacox2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_xaxacox3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_xaxacox4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_xaxacox5);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_xaxacox6);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_xaxacox7);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_xaxacox8);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_xaxacox9);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_xaxacox10);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_xaxacox11);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_xaxacox12);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_xaxacox13);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_xaxacox14);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_xaxacox15);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_xaxacox16);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_xaxacox17);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_xaxacox18);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_t_xaxacox19);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.d_t_xaxacox20);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.trnox_cit1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.trnox_cit2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.trnox_cit3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.trnox_cit4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_d_h1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_d_h2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_d_h3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_d_h4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_d1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_d2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_d3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_d4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_d_s1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_d_s2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_d_s3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_d_s4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_h1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_h2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_h3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_h4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_hp1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_hp2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_hp3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_hp4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_s_d_h1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_s_d_h2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_s_d_h3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_s_d_h4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_s_h1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_s_h2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_s_h3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_s_h4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_s1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_s2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_s3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_s4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_t_d_h1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_t_d_h2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_d_h3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_d_h4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_t_d_s_h1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_t_d_s_h2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_s_d_h3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_s_d_h4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_t_d_s1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_t_d_s2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_d_s3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_d_s4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_t_d1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_t_d2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_d3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_d4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_t_h1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_t_h2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_h3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_h4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_t_s_h1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_t_s_h2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_s_h3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_s_h4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_t_s1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_t_s2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_s3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_s4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_t1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.f_t2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.trnox_cit3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.trnox_cit4);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.tprtacox1);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.tprtacox2);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.tprtacox3);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.tprtacox4);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.tprtacox5);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.tprtacox6);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.tprtacox7);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.tprtacox8);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.tprtacox9);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.tprtacox10);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.tprtacox11);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.tprtacox12);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.tprtacox13);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.tprtacox14);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d1);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d2);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d3);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d4);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d5);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d6);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d7);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d8);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d9);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d10);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d11);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d12);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d13);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d14);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_h1);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_h2);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_h3);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_h4);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_h5);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_h6);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_h7);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_h8);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_h9);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_h10);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_h11);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_h12);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_h13);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_h14);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d_h1);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d_h2);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d_h3);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d_h4);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d_h5);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d_h6);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d_h7);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d_h8);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d_h9);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d_h10);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d_h11);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d_h12);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d_h13);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.ht_d_h14);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox1);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox2);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox3);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox4);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox5);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox6);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox7);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox8);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox9);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox10);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox11);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox12);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox13);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox14);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox15);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox16);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox17);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox18);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox19);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox20);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox21);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox22);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox23);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox24);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox25);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox26);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox27);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox28);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox29);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox30);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox31);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox32);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox33);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox34);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox35);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox36);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox37);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox38);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox39);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox40);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox41);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox42);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox43);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox44);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox45);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox46);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox47);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvox48);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.qnac1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.qnac2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.sl_d_h1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.sl_d_h2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.sl_d_s_h1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.sl_d_s_h2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.sl_d_s1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.sl_d_s2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.sl_d_h1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.sl_d_h2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.sl_d1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.sl_d2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.sl_h1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.sl_h2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.sl_hp1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.sl_hp2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.sl_s_h1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.sl_s_h2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.sl_s1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.sl_s2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_9);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_10);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_s_1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_s_2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_s_3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_s_4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_s_5);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_s_6);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_s_7);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_s_8);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_s_9);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_s_10);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_t_1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_t_2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_t_3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_t_4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_t_5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_t_6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_t_7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_t_8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_t_9);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_t_10);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_t_s_1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_t_s_2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_t_s_3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_t_s_4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_t_s_5);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_t_s_6);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_t_s_7);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_t_s_8);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_t_s_9);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_d_t_s_10);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_s_1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_s_2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_s_3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_s_4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_s_5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_s_6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_s_7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_s_8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_s_9);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_s_10);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_t_1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_t_2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_t_3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_t_4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_t_5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_t_6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_t_7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_t_8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_t_9);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_t_10);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_t_s_1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_t_s_2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_t_s_3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_t_s_4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_t_s_5);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_t_s_6);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_t_s_7);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_t_s_8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_t_s_9);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_t_s_10);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_hp_1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_hp_2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_hp_3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_hp_4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_hp_5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_hp_6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_hp_7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_hp_8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.e_hp_9);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.e_hp_10);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.chervyak);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.mc1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.mc2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.mc3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.mc4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.mc5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.mc6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.mc7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.mc8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.mc9);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mc10);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.petur);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mp1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mp2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mp3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mp4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mp5);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mp6);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mp7);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mp8);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mp9);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.mp10);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.mp11);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.mp12);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.mp13);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.mp14);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.mp15);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.qnel);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.mq1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.mq2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.mq3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.mq4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.mq5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.mq6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.mq7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.mq8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.mq9);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq10);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq11);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq12);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq13);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq14);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq15);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq16);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq17);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq18);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq19);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq20);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq21);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq22);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq23);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq24);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq25);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq26);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq27);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq28);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq29);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq30);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq31);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq32);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq33);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq34);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq35);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq36);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq37);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq38);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq39);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq40);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq41);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq42);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq43);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq44);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq45);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq46);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq47);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq48);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq49);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq50);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq51);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq52);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq53);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq54);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq55);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq56);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq57);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq58);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq59);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.mq60);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.qaq1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.qaq2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.qaq3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.qaq4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.qaqox1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.qaqox2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.qaqox3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.qaqox4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.qaqox5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.qaqox6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.qaqox7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.qaqox8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.qaqox9);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.qaqox10);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_h1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_h2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_h3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_h4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_h5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_h6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_h7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_h8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_h9);
        LoadingBitmapArray[i++] =BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_h10);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_s_h1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_s_h2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_s_h3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_s_h4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_s_h5);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_s_h6);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_s_h7);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_s_h8);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_s_h9);
        LoadingBitmapArray[i++] =BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_s_h10);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_s1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_s2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_s3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_s4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_s5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_s6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_s7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_s8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_s9);
        LoadingBitmapArray[i++] =BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_s10);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_h1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_h2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_h3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_h4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_h5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_h6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_h7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_h8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_h9);
        LoadingBitmapArray[i++] =BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_h10);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_s_h1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_s_h2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_s_h3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_s_h4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_s_h5);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_s_h6);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_s_h7);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_s_h8);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_s_h9);
        LoadingBitmapArray[i++] =BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_s_h10);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_s1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_s2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_s3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_s4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_s5);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_s6);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_s7);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_s8);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_s9);
        LoadingBitmapArray[i++] =BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t_s10);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t9);
        LoadingBitmapArray[i++] =BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d_t10);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d9);
        LoadingBitmapArray[i++] =BitmapFactory.decodeResource(context.getResources(), R.drawable.p_d10);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h_s1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h_s2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h_s3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h_s4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h_s5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h_s6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h_s7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h_s8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h_s9);
        LoadingBitmapArray[i++] =BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h_s10);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h9);
        LoadingBitmapArray[i++] =BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h10);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_s1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_s2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_s3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_s4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_s5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_s6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_s7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_s8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_s9);
        LoadingBitmapArray[i++] =BitmapFactory.decodeResource(context.getResources(), R.drawable.p_s10);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_h1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_h2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_h3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_h4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_h5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_h6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_h7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_h8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_h9);
        LoadingBitmapArray[i++] =BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_h10);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_s_h1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_s_h2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_s_h3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_s_h4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_s_h5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_s_h6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_s_h7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_s_h8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_s_h9);
        LoadingBitmapArray[i++] =BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_s_h10);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_s1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_s2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_s3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_s4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_s5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_s6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_s7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_s8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_s9);
        LoadingBitmapArray[i++] =BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t_s10);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_h1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t9);
        LoadingBitmapArray[i++] =BitmapFactory.decodeResource(context.getResources(), R.drawable.p_t10);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.foin7);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.foin7);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.foin1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.foin2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.foin3);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.foin4);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.foin5);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.foin6);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.foin7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.level1);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.level2);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.level3);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.level4);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.level5);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.level6);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.level7);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.level8);
        LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(), R.drawable.level9);
        LoadingBitmapArray[i++] =BitmapFactory.decodeResource(context.getResources(), R.drawable.level10);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.level11);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.level12);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.level13);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.level14);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.level15);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.level16);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.level17);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.level18);
       LoadingBitmapArray[i++]= BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvelu_knopka);
       LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvelu_knopka);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvelu_knopkaa);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.lvacvelu_knopka_mug);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.background1);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.background2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.kustik2);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.kustik);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(), R.drawable.srtik);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.kextik);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.tarelka);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.zzz);
        LoadingBitmapArray[i++] = BitmapFactory.decodeResource(context.getResources(),R.drawable.smilik);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(), R.drawable.chervyak);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(), R.drawable.petur);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(), R.drawable.qnel);
        LoadingBitmapArray[i++]=  BitmapFactory.decodeResource(context.getResources(), R.drawable.utelu_knopkaa);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(), R.drawable.xaxalu_knopkaa);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(), R.drawable.qnelu_knopkaa);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.screenshot);
        LoadingBitmapArray[i++] =  BitmapFactory.decodeResource(context.getResources(),R.drawable.xanut);
        // Update the progress using a handler or a progress listener
    }
    @Override
    protected void onDestroy() {
        super.onDestroy();
        currentDate = new Date();
        editor = timePassedsp.edit();
        timeText = timeFormat.format(currentDate);
        timePassed = ((timeText.indexOf(0)*10+timeText.indexOf(1))*3600)+((timeText.indexOf(3)*10+timeText.indexOf(4))*60)+((timeText.indexOf(6)*10+timeText.indexOf(7)));
        editor.putInt("TIMEPASSED",timePassed);
        editor.apply();
        mediaPlayer.stop();
    }
    @Override
    protected void onStop() {
        super.onStop();
        currentDate = new Date();
        editor = timePassedsp.edit();
        timeText = timeFormat.format(currentDate);
        timePassed = ((timeText.indexOf(0)*10+timeText.indexOf(1))*3600)+((timeText.indexOf(3)*10+timeText.indexOf(4))*60)+((timeText.indexOf(6)*10+timeText.indexOf(7)));
        editor.putInt("TIMEPASSED",timePassed);
        editor.apply();
        mediaPlayer.stop();
    }

}